### ISSUE TITLE
Add more parameters for the fitting in the quick fits for TESS tutorial.

### ISSUE THREAD

**Issue by xylm2021** [exoplanet-dev/case-studies#35]
Hi, in the quick fits for TESS tutorial, is it possible to add more parameters for the fitting? Especially the transit depth, the ratio between semi-major axis to stellar radius and the orbital  inclination angle? As these parameters can be shown in the Mandel-Agol fitting process using VARTOOLS (https://www.astro.princeton.edu/~jhartman/vartools/EXAMPLE_HTML/mandelagoltransit.html). Thanks!

**Comment by dfm** [comment]
Sure, you can fit whatever parameters you want! `exoplanet` doesn't decide which parameters make sense for a particular application, that's up to you :D

A good resource for looking at the relationships between parameters is: https://arxiv.org/abs/1001.2010

**Comment by xylm2021** [comment]
> Sure, you can fit whatever parameters you want! `exoplanet` doesn't decide which parameters make sense for a particular application, that's up to you :D
> 
> A good resource for looking at the relationships between parameters is: https://arxiv.org/abs/1001.2010

OK, thanks! I will try to do it by myself.
