### ISSUE TITLE
findfont: Generic family 'sans-serif' not found because none of the following families were found: Liberation Sans

### ISSUE THREAD

**Issue by JosephKarpinski** [exoplanet-dev/case-studies#64]
Exoplanet seems to corrupt matplotlib.
exoplanet.__version__ = '0.5.3'

Tried multiple Conda environments Python 3.7, 3.8, 3.10, 3.11

Adding test code shows matplotlib working normally until:
 import exoplanet.

Then every matplotlib cell generates many:
findfont: Generic family 'sans-serif' not found because none of the following families were found: Liberation Sans

astrometric.ipynb has the above issue initially in Python 3.7 until code:
The plot on the sky is helpful to look at, but the "raw" measurements are the values of $\rho$ (separation) and $\theta$ (also called P.A., position angle) that we listed in our data table, and that the measurement uncertainties live on these values as nice Gaussians. So, to visualize this space more clearly, we can plot $\rho$ vs. time and P.A. vs. time.

Then lower cells in Python 3.7 work without issue with matplotlib.
Higher Python versions have the above issue continuously.

<img width="1134" alt="Screen Shot 2023-08-16 at 10 41 10 AM" src="https://github.com/exoplanet-dev/case-studies/assets/37123616/f932bf44-553c-4aad-940e-10da593040df">

<img width="1134" alt="Screen Shot 2023-08-16 at 10 41 37 AM" src="https://github.com/exoplanet-dev/case-studies/assets/37123616/a0a43bf2-acd0-459f-a570-64da567b1064">

<img width="1134" alt="Screen Shot 2023-08-16 at 10 41 47 AM" src="https://github.com/exoplanet-dev/case-studies/assets/37123616/3f342ad3-4515-4dad-a694-b215dcf257c1">

<img width="1134" alt="Screen Shot 2023-08-16 at 10 45 11 AM" src="https://github.com/exoplanet-dev/case-studies/assets/37123616/18d98328-0dca-49bd-8bdf-da71b0c7263d">

Matplotlib Test case:

<img width="1134" alt="Screen Shot 2023-08-16 at 10 43 52 AM" src="https://github.com/exoplanet-dev/case-studies/assets/37123616/8fc086b0-bc87-418b-9586-b4ade26c36b5">

After import exoplanet:

<img width="1134" alt="Screen Shot 2023-08-16 at 10 46 08 AM" src="https://github.com/exoplanet-dev/case-studies/assets/37123616/66eda2e3-972f-4191-9762-289bba7a83cd">

**Comment by JosephKarpinski** [comment]
MacOS: 12.6.7

<img width="597" alt="Screen Shot 2023-08-16 at 11 33 43 AM" src="https://github.com/exoplanet-dev/case-studies/assets/37123616/e0047ecc-c339-43fc-b9b9-830a562ad447">

**Comment by dfm** [comment]
If you don't want to use these plotting styles, you shouldn't call `docs_setup` and exoplanet won't change any matplotlib settings!

**Comment by JosephKarpinski** [comment]
That worked.
Thanks!

Please close.
